# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58cb4f7d141dd331b0f23a46ff80f3be1b9d9b82d5506f5d7c28a0292aa8fb60d98a5840b3f018d827133762a922974c39a8056c864c535262a8b0dcc929231c

test:
  secret_key_base: 4a35e789854e85c13beb127e57ac0e09a6df38641fe4ee2d2ab7874097830b80edbb73e8bd3b1ca28d4de1d626d8047faca16329cf1099c5297fdb3a48cd74b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
